apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: logging
data:
  otel-collector-config.yaml: |
    receivers:
      # Collecte des logs du système
      filelog:
        include: [/var/log/containers/*.log]
        start_at: beginning
        operators:
          - type: container
          - type: json_parser
            if: 'body matches "^\\s*\\{"'
            parse_from: body
            parse_to: body
          - type: move
            from: body.log
            to: body.message
          - type: move
            from: body.time
            to: attributes.time
          - type: add
            field: resource["k8s.cluster.name"]
            value: "challengr-minikube"
          - type: add
            field: resource["service.name"]
            value: "unknown-service"

    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_mib: 200
        spike_limit_mib: 20
      attributes:
        actions:
          - key: environment
            value: dev
            action: insert

    exporters:
      loki:
        endpoint: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
        default_labels_enabled:
          exporter: true
          job: true
          instance: true
          service: true
          namespace: true
      logging: 
        loglevel: info

    service:
      telemetry:
        logs:
          level: info
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, attributes]
          exporters: [loki, logging]
