apiVersion: apps/v1
kind: Deployment
metadata: { name: challenge-service, namespace: challengr }
spec:
  replicas: 1
  selector: { matchLabels: { app: challenge-service } }
  template:
    metadata: { labels: { app: challenge-service } }
    spec:
      containers:
        - name: app
          image: challenge-service:0.1
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 8080 } ]
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/challengr"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              value: "dev-secret-please-change-32-bytes"
#            - name: JAVA_TOOL_OPTIONS
#              value: >
#                -javaagent:/otel/opentelemetry-javaagent.jar
#                -Dotel.service.name=challenge-service
#                -Dotel.exporter.otlp.endpoint=http://otel-collector:4317
#          volumeMounts:
#            - name: otel-agent
#              mountPath: /otel
#      volumes:
#        - name: otel-agent
#          configMap:
#            name: otel-javaagent
---
apiVersion: v1
kind: Service
metadata: { name: challenge-service, namespace: challengr }
spec:
  selector: { app: challenge-service }
  ports: [ { port: 8080, targetPort: 8080 } ]
