apiVersion: apps/v1
kind: Deployment
metadata: { name: submission-service, namespace: challengr }
spec:
  replicas: 1
  selector: { matchLabels: { app: submission-service } }
  template:
    metadata: { labels: { app: submission-service } }
    spec:
      containers:
        - name: app
          image: submission-service:0.1
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 8081 } ]
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/challengr"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              value: "dev-secret-please-change-32-bytes"
#            - name: JAVA_TOOL_OPTIONS
#              value: >
#                -javaagent:/otel/opentelemetry-javaagent.jar
#          volumeMounts:
#            - name: otel-agent
#              mountPath: /otel
#            - name: uploads
#              mountPath: /uploads
#      volumes:
#        - name : uploads
#          emptyDir: {}
#        - name: otel-agent
#          configMap:
#            name: otel-javaagent

---
apiVersion: v1
kind: Service
metadata: { name: submission-service, namespace: challengr }
spec:
  selector: { app: submission-service }
  ports: [ { port: 8081, targetPort: 8081 } ]
