apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: challengr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: otel-agent-downloader
          image: curlimages/curl:8.6.0
          command: [ "sh", "-c" ]
          args:
            - |
              echo "📥 Téléchargement de l’agent OpenTelemetry..." && \
              curl -fsSL -o /otel/opentelemetry-javaagent.jar \
              https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.12.0/opentelemetry-javaagent.jar && \
              echo "✅ Agent téléchargé avec succès."
          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      containers:
        - name: auth-service
          image: auth-service:v2025-10-19-01h24m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082

          env:
            - name: JWT_SECRET
              value: "super-ultra-long-secret-key-1234567890-!!!"
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Dlogging.config=classpath:logback-spring.xml
                -javaagent:/otel/opentelemetry-javaagent.jar
                -Dotel.service.name=auth-service
                -Dotel.exporter.otlp.endpoint=http://otel-collector.logging.svc.cluster.local:4317
                -Dotel.exporter.otlp.protocol=grpc
                -Dotel.logs.exporter=otlp
                -Dotel.metrics.exporter=otlp
                -Dotel.traces.exporter=otlp
                -Dotel.resource.attributes=deployment.environment=dev

          volumeMounts:
            - name: otel-agent
              mountPath: /otel
              readOnly: true

      volumes:
        - name: otel-agent
          emptyDir: { }

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: challengr
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
