server.port=8081
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/challengr}
spring.datasource.username=${DB_USER:challengr}
spring.datasource.password=${DB_PASS:challengr}
spring.jpa.hibernate.ddl-auto=update
